name: datadog-actions-metrics
description: submit metrics of GitHub Actions to Datadog

inputs:
  github-token:
    description: GitHub token to get jobs and steps if needed
    default: ${{ github.token }}
    required: true
  github-token-rate-limit-metrics:
    description: GitHub token for rate limit metrics
    default: ${{ github.token }}
    required: true
  datadog-api-key:
    description: Datadog API key (dry-run if not set)
    required: false
  datadog-site:
    description: Datadog Site name if different than datadoghq.com.
    required: false
  collect-job-metrics:
    description: Collect metrics of jobs and steps
    required: false
    default: 'false'
  collect-job-metrics-for-only-default-branch:
    description: No longer supported
    required: false
    deprecationMessage: Use collect-job-metrics instead

runs:
  using: 'node16'
  main: 'dist/index.js'
