name: datadog-actions-metrics
description: submit metrics of GitHub Actions to Datadog
inputs:
  github-token:
    description: GitHub token
    default: ${{ github.token }}
    required: true
  datadog-api-key:
    description: Datadog API key (dry-run if not set)
    required: false
  collect-job-metrics-for-only-default-branch:
    description: Collect job metrics only for the default branch
    required: true
    default: 'true'
runs:
  using: 'node12'
  main: 'dist/index.js'
