name: datadog-actions-metrics
description: submit metrics of GitHub Actions to Datadog
inputs:
  github-token:
    description: GitHub token
    default: ${{ github.token }}
    required: true
  datadog-api-key:
    description: Datadog API key (dry-run if not set)
    required: false
  collect-job-metrics:
    description: Collect metrics of jobs and steps
    required: false
    default: 'false'
  collect-job-metrics-for-only-default-branch:
    description: No longer supported
    required: false
    deprecationMessage: Use collect-job-metrics instead
runs:
  using: 'node12'
  main: 'dist/index.js'
