name: datadog-actions-metrics
description: submit metrics of GitHub Actions to Datadog

inputs:
  github-token:
    description: GitHub token to get jobs and steps if needed
    default: ${{ github.token }}
    required: true
  github-token-rate-limit-metrics:
    description: GitHub token for rate limit metrics
    default: ${{ github.token }}
    required: true

  datadog-api-key:
    description: Datadog API key (dry-run if not set)
    required: false
  datadog-site:
    description: Datadog Site name if different than datadoghq.com.
    required: false
  datadog-tags:
    description: Additional tags in the form of `key:value` in a multiline string
    required: false

  collect-job-metrics:
    description: Collect job metrics
    required: false
    default: 'false'
  collect-step-metrics:
    description: Collect step metrics
    required: false
    default: 'false'
  send-pull-request-labels:
    description: Send pull request labels as Datadog tags
    required: false
    default: 'false'
  disable-distribution-metrics:
    description: If true, do not send the distribution metrics
    required: false
    default: 'false'

  filtered-metrics:
    description: Metrics to collect
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
