name: datadog-actions-metrics
description: submit metrics of GitHub Actions to Datadog

inputs:
  github-token:
    description: GitHub token to get jobs and steps if needed
    default: ${{ github.token }}
    required: true
  github-token-rate-limit-metrics:
    description: GitHub token for rate limit metrics
    default: ${{ github.token }}
    required: true

  datadog-api-key:
    description: Datadog API key (dry-run if not set)
    required: false
  datadog-site:
    description: Datadog Site name if different than datadoghq.com.
    required: false
  datadog-tags:
    description: Additional tags in the form of `key:value` in a multiline string
    required: false
  metrics-patterns:
    description: Filter the metrics by patterns in a multiline string
    required: false
  tag-key-patterns:
    description: Filter the tag keys by patterns in a multiline string
    required: false

  collect-job-metrics:
    description: Collect job metrics
    required: false
    default: 'false'
  collect-step-metrics:
    description: Collect step metrics
    required: false
    default: 'false'
  prefer-distribution-workflow-run-metrics:
    description: If true, send the distribution metrics instead of gauge metrics
    required: false
    default: 'false'
  prefer-distribution-job-metrics:
    description: If true, send the distribution metrics instead of gauge metrics
    required: false
    default: 'false'
  prefer-distribution-step-metrics:
    description: If true, send the distribution metrics instead of gauge metrics
    required: false
    default: 'false'
  send-pull-request-labels:
    description: Send pull request labels as Datadog tags
    required: false
    default: 'false'
  collect-job-metrics-realtime:
    description: Collect job metrics in real-time as jobs complete (requires workflow_job event)
    required: false
    default: 'false'

runs:
  using: 'node20'
  main: 'dist/index.js'
