name: release

on:
  pull_request:
    paths:
      - .github/workflows/release.yaml
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  tag:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
          package-manager-cache: false
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm build
      - uses: int128/release-typescript-action@a935ad8ccd881c793df1abe68d05090d6b898d02 # v1.55.0
