name: wait-for-workflows

on:
  pull_request:

jobs:
  wait-for-workflows:
    runs-on: ubuntu-slim
    timeout-minutes: 15
    steps:
      - uses: int128/wait-for-workflows-action@ecb557dfcf83b82593cd728bd7b84775f27be669 # v1.76.0
